# Generated by Django 3.2.6 on 2021-08-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_poster', models.CharField(default='Anonymous', max_length=50, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('job_post', models.TextField()),
                ('item_type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], default='job', max_length=50)),
                ('job_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('total_comments', models.IntegerField(blank=True, null=True)),
                ('story_link', models.URLField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], default='story', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], default='comment', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.story')),
            ],
        ),
    ]
