# Generated by Django 3.2.6 on 2021-08-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20210810_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='story_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_app.story'),
        ),
    ]
