# Generated by Django 3.2.6 on 2021-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_remove_story_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='news_image',
            field=models.ImageField(default='no_image.png', upload_to='news_image'),
        ),
    ]
